class Food{
  String name;
  int type;
  String imageUrl;
  List<String> ingredients;
  List<String> recipe;
  Food(
      this.name,
      this.type,
      this.imageUrl,
      this.ingredients,
      this.recipe,
      );
  static List<Food> turkeys=[
    Food(
      'Salted Roast Turkey with Herbs and Shallot-Dijon Gravy',
      1,
      'turkey1.jpg',
      [ '1/3 cup plus 1 tablespoon coarse kosher salt',
        '2 1/2 teaspoons dried rosemary',
        '2 1/2 teaspoons dried rubbed sage',
        '2 1/2 teaspoons dried thyme',
        '1 teaspoon black peppercorns, crushed',
        '3 small bay leaves, coarsely torn',
        '1 teaspoon finely grated lemon peel',
        '1 14- to 16-pound turkey (neck, heart, and gizzard reserved)',
        '1 large onion, chopped',
        '1 large celery stalk, chopped',
        '1 whole lemon, chopped with peel',
        '1/2 cup (1 stick) unsalted butter, room temperature',
        '5 cups (or more) Golden Turkey Stock',
        '2/3 cup chopped shallots',
        '1/2 cup all purpose flour',
        '1/2 cup dry white wine',
        '2 tablespoons Dijon mustard',
        '2 teaspoons chopped fresh rosemary',
      ],
      ['1. Rub first 6 ingredients in small bowl to crush herbs finely. DO AHEAD: Can be made 1 week ahead. Cover; store at room temperature. Stir in peel before using.\n',
       '2. Rinse turkey inside and out (do not pat dry). Pull any fat pads from main cavity and neck cavity of turkey; wrap, chill, and reserve fat for roasting. Place turkey in roasting bag; sprinkle inside and '
          'out with herbed salt. Close bag. Place on baking sheet; refrigerate 18 to 24 hours.\n',
        '3. Set rack at lowest position in oven and preheat to 325°F. Rinse turkey inside and out; pat very dry. Stir chopped onion and next 5 ingredients in small bowl. Divide onion mixture between main and neck cavities. Fold neck skin under and secure with skewer. Tuck wing tips under. Tie legs together loosely. Place turkey on rack set in large roasting pan. Spread butter all over turkey. Place reserved fat pads and reserved neck, heart, and gizzard in pan; pour in 2 cups Golden Turkey Stock.\n',
        '4. Roast turkey 45 minutes. Baste with pan juices. Continue to roast until thermometer inserted into thickest part of thigh registers 165°F to 170°F, basting every 45 minutes, adding stock or water to pan if dry, and tenting loosely with foil if browning too quickly, 3 to 3 1/2 hours longer. Transfer turkey to platter; tent very loosely with foil and let rest 30 to 45 minutes. Reserve roasting pan with juices for gravy.\n',
        '5. Remove turkey neck, heart, and gizzard from roasting pan. Pull meat off neck; chop neck meat, heart, and gizzard and reserve for gravy, if desired. Pour pan juices into 8-cup measuring cup. Spoon off fat from surface, reserving 1/2 cup fat. Add enough turkey stock to degreased pan juices to measure 5 1/2 cups total.\n',
        '6. Place roasting pan over 2 burners on medium heat. Add 1/2 cup reserved fat and shallots; sauté 1 minute. Whisk in flour. Cook until roux is light brown, whisking constantly, about 2 minutes. Whisk in wine, stock mixture, mustard, and fresh rosemary. Bring to boil, whisking to blend. Boil until gravy coats spoon, about 3 minutes. Add neck, heart, and gizzard, if desired. Season with salt and pepper.\n',
        '7. Serve turkey with gravy.\n',
      ],
    ),
    Food(
      'Bourbon and Brown Sugar Glazed Turkey',
      1,
      'turkey2.jpg',
      [ '6 tablespoons kosher salt',
        '4 tablespoons black peppercorns, medium ground',
        '1 tablespoon granulated sugar',
        '1 tablespoon paprika',
        '1 (12–14-pound) turkey',
        '1 head of garlic, cut in half crosswise',
        '2 sprigs rosemary',
        'Olive oil (for cooking; 5–7 cups)',
        '1/2 cup (packed) light brown sugar',
        '1/2 cup bourbon',
        '2 tablespoons soy sauce',
        '2 tablespoons unsalted butter',
        '1 teaspoon paprika',
      ],
      ['1. Mix salt, pepper, granulated sugar, and paprika in a small bowl. Arrange turkey on a cutting board breast side up. Remove legs (keeping thigh and drumstick intact) by slicing through the skin that joins breast and leg, then bend leg down to expose joint and cut completely through the joint. Try to leave as much skin on breast as possible. Place legs on a large rimmed baking sheet. Set aside neck and giblets in cavity for making gravy. Arrange turkey on baking sheet with legs and generously sprinkle legs and turkey all over with dry brine, patting to adhere. Chill, uncovered, at least 12 hours and up to 2 days\n',
      '2. Wipe off turkey legs (do not rinse) and place in the smallest heavy pot that will accommodate legs in a single layer (it’s okay if they overlap slightly). Add garlic and rosemary. Pour in oil just to barely cover legs. Heat over medium until a few bubbles begin to appear. Cover, reduce heat, and very gently simmer until meat is tender (the meat on the drumstick will have pulled away from the bone), 3–3 1/2 hours. Let turkey thighs cool in oil until just warm, about 2 hours. Chill at least 2 hours but preferably longer. Meat will firm up the colder it gets, making it less likely to fall apart when glazing.\n',
        '3. Preheat oven to 425°F. Place turkey on a wire rack set inside a large rimmed baking sheet. Roast, rotating baking sheet once, until golden brown all over, 35–40 minutes.\n',
        '4. Meanwhile, bring brown sugar, bourbon, soy sauce, butter, and paprika to a simmer in a small saucepan over medium heat, stirring occasionally, until reduced by about half and thick enough to coat a spoon but not syrupy, 6–8 minutes. Reduce heat to very low and keep glaze warm until ready to use.\n',
        '5. Reduce oven temperature to 325°F and roast turkey until an instant-read thermometer inserted into the thickest part of breast registers 100°F–110°F. Then roast, basting every 10 minutes or so, making sure to lightly coat the entire breast each time (but save some glaze for the legs) and rotating baking sheet occasionally, until thermometer registers 150°F, 60–75 minutes total after reducing oven temperature to 325°F. Transfer breast to a cutting board and let rest at least 30 minutes before carving.\n',
        '6. Increase oven temperature back to 425°F. Remove turkey legs from oil, wiping off excess, and place on a clean rimmed baking sheet; discard or chill cooking oil (skim off juices and use them in gravy; use oil for cassoulet or another confit).\n',
        '7. Carefully move a rack to upper third of oven and roast legs until skin is golden brown and fat is rendered, 15–20 minutes. Then roast, basting every 3 minutes or so with remaining glaze, until legs are well coated, 10–12 minutes. Arrange on a platter with sliced breast for serving.\n',
        '8. Legs can be cooked 1 day ahead. Keep chilled in oil.\n',
      ],
    ),
    Food(
      'Butter-Roasted Turkey Breasts',
      1,
      'turkey3.jpg',
      ['2 skin-on, bone-in turkey breasts (3 1/2–4 pounds)',
        '1/2 cup (1 stick) unsalted butter, room temperature',
        'Kosher salt, freshly ground pepper',
        '6 sprigs thyme',
        '4 sprigs rosemary',
        '1 head of garlic, cloves peeled, crushed',
      ],
      ['1. Preheat oven to 425°F. Gently loosen skin from turkey breasts and rub butter under skin and all over outside of breasts; season with salt and pepper.\n',
        '2. Scatter thyme sprigs, rosemary sprigs, and garlic over a large rimmed baking sheet and arrange turkey breasts, skin side up, on top. Roast turkey breasts, turning halfway through, until skin is crisp and golden brown and an instant-read thermometer inserted into the thickest part of breasts registers 160°F (for optimal moistness, you will want to cook the white meat of the turkey breasts to a lower internal temperature than you would if cooking a whole bird), 45–55 minutes.\n',
        '3. Transfer turkey breasts to a platter and let rest 10 minutes before carving.\n',
        '4. Serve turkey breasts with pan drippings alongside.\n',
      ],
    ),
    ];
  static List<Food> drinks=[
    Food(
      'Apricot-Apple Cider',
      2,
      'drink1.jpg',
      ['8 cups unsweetened apple juice',
      '1 can (12 ounces) ginger ale',
      '1/2 cup dried apricots, halved',
      '1/2 cup dried cranberries',
      '1 tablespoon whole allspice',
      '1 tablespoon whole cloves',],
      ['1. In a 5-qt. slow cooker, combine apple juice and ginger ale. Place the apricots, cranberries, cinnamon sticks, allspice and cloves on a double thickness of cheesecloth; bring up corners of cloth and tie with string to form a bag. Place in slow cooker; cover.\n',
      '2. Cook on high until heated through, 3-4 hours. Discard spice bag.\n',
      ],
    ),
    Food(
      'Cranberry Fizz',
      2,
      'drink2.jpg',
      ['1 bottle (32 ounces) cranberry juice',
      '1 cup orange juice',
      '1 cup ruby red grapefruit juice',
      '1/2 cup sugar',
      '2 cups ginger ale, chilled',
      'Orange slices and fresh or frozen cranberries',],
      ['1. In a pitcher, combine cranberry, orange and grapefruit juices and sugar. Refrigerate, covered, until chilled. Just before serving, stir in ginger ale. To serve, pour mixture over ice. Garnish with orange slices and cranberries if desired.\n',],
    ),
    Food(
      'Pumpkin Spice Hot Chocolate',
      2,
      'drink3.jpg',
      ['1 cup heavy whipping cream',
      '3 tablespoons sugar',
      '3 tablespoons sugar',
      '8 cups 2% milk',
      '4 cups heavy whipping cream',
      '2 cinnamon sticks (3 inches)',
      '2 tablespoons pumpkin pie spice',
      '1 tablespoon grated orange zest',
      '1 can (15 ounces) pumpkin',
      '1 cup sugar',
      '1 cup white baking chips',
      '1 tablespoon vanilla extract',
      'Additional pumpkin pie spice',],
      ['1. In a medium bowl, beat cream until it begins to thicken. Add sugar and vanilla; beat until stiff peaks form. Refrigerate until serving.\n',
      '2. In a 6-qt. stockpot, heat milk, cream, cinnamon sticks, pie spice and orange zest over medium heat until bubbles form around sides of pan.\n',
      '3. Whisk pumpkin, sugar and baking chips into milk mixture until blended. Remove from heat; stir in vanilla. Discard cinnamon sticks. Pour into mugs; top with whipped cream. Sprinkle with additional pumpkin pie spice. Serve immediately.\n',],
    ),
    ];
  static List<Food> desserts= [
    Food(
      'Mile-High Cranberry Meringue Pie',
      3,
      'dessert1.jpg',
      ['4 large eggs, separated',
      'Pastry for single-crust pie (9 inches)',
      '4 cups fresh or frozen cranberries, thawed',
      '2-1/4 cups sugar, divided',
      '2-1/4 cups sugar, divided',
      '2 tablespoons all-purpose flour',
      '1/4 teaspoon salt',
      '2 tablespoons butter',
      '2 teaspoons vanilla extract, divided',
      '1/2 teaspoon cream of tartar'],
      ['1. Preheat oven to 425°. Let egg whites stand 30 minutes at room temperature.\n',
      '2. On a lightly floured surface, roll dough to a 1/8-in.-thick circle; transfer to a 9-in. pie plate. Trim crust to 1/2 in. beyond rim of plate; flute edge. Refrigerate 30 minutes.\n',
      '3. Line unpricked crust with a double thickness of foil. Fill with pie weights, dried beans or uncooked rice. Bake on a lower oven rack 15-20 minutes or until edges are light golden brown. Remove foil and weights; bake 3-6 minutes longer or until bottom is golden brown. Cool on a wire rack. Reduce heat to 325°.\n',
      '4. In a large saucepan, combine cranberries, 1-1/2 cups sugar and water. Bring to a boil, stirring to dissolve sugar. Reduce heat to medium; cook, uncovered, 4-6 minutes or until berries stop popping, stirring occasionally. Remove from heat. In a small bowl, whisk egg yolks, 1/4 cup sugar, flour and salt until blended. Gradually whisk in 1/2 cup of hot cranberry liquid; return all to saucepan, stirring constantly. Bring to a gentle boil; cook and stir 2 minutes. Remove from heat; stir in butter and 1 teaspoon vanilla.\n',
      '5. For meringue, beat egg whites with cream of tartar and remaining vanilla on medium speed until foamy. Add remaining sugar, 1 tablespoon at a time, beating on high after each addition until sugar is dissolved. Continue beating until stiff glossy peaks form. Transfer hot filling to pastry. Spread meringue evenly over hot filling, sealing to edge of pastry. Bake 25-30 minutes or until meringue is golden brown. Cool 1 hour on a wire rack. Refrigerate at least 4 hours before serving.\n',
      ],
    ),
    Food(
      'Caramel Pecan Pie',
      3,
      'dessert2.jpg',
      ['36 caramels',
      '1/4 cup water',
      '1/4 cup butter, cubed',
      '3 large eggs, room temperature',
      '3/4 cup sugar',
      '1 teaspoon vanilla extract',
      '1/8 teaspoon salt',
      '1-1/3 cups chopped pecans, toasted',
      '1 frozen deep-dish pie crust (9 inches)',
      'Pecan halves'],
      ['1. Preheat oven to 350°. In a small heavy saucepan, combine the caramels, water and butter. Cook and stir over low heat until caramels are melted. Remove from the heat and set aside.\n',
      '2. In a small bowl, beat the eggs, sugar, vanilla and salt until smooth. Gradually add caramel mixture. Stir in chopped pecans. Pour into crust. If desired, arrange pecan halves over filling.\n',
      '3. Bake until set, 35-40 minutes. Cool on a wire rack. Refrigerate leftovers.\n'],
    ),
    Food(
      'Molasses Pumpkin Pie',
      3,
      'dessert3.jpg',
      ['Dough for single-crust pie',
      '2 large eggs',
      '1/2 cup sugar',
      '1 teaspoon ground cinnamon',
      '1/2 teaspoon salt',
      '1/2 teaspoon ground ginger',
      '1/2 teaspoon ground nutmeg',
      '1 can (15 ounces) pumpkin',
      '3 tablespoons molasses',
      '3/4 cup evaporated milk',
      'Whipped topping'],
      ['1. On a lightly floured surface, roll dough to a 1/8-in.-thick circle; transfer to a 9-in. pie plate. Trim to 1/2 in. beyond edge of plate; flute edge. Set aside.\n',
      '2. In a large bowl, beat the eggs, sugar, cinnamon, salt, ginger and nutmeg. Beat in pumpkin and molasses; gradually add milk. Pour into crust. Cover edge loosely with foil.\n',
      '3. Bake at 425° for 10 minutes. Remove foil. Reduce heat 350°; bake 28-32 minutes longer or until a knife inserted in the center comes out clean. Cool on a wire rack for 2 hours. Chill until ready to serve. Serve with whipped topping. Refrigerate leftovers.\n',],
    ),
  ];
}